name: Candy2
version: '${project.version}'
main: commandercortex.candy2.Candy2
api-version: '1.20'
load: STARTUP
commands:
  group:
    description: Set a players Group
  fly:
    description: Allows staff to fly in any game mode
  gm:
    description: Gamemode Command
  v:
    description: Vanishes a Player (for staff)
  cc:
    description: Clears Chat
